apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2020-07-13T21:06:19Z"
  generation: 1
  labels:
    app: web
  name: web
  namespace: default
  resourceVersion: "1794120"
  selfLink: /apis/apps/v1/namespaces/default/deployments/web
  uid: 214bffcb-6a24-4a76-9dbf-9a4f35a19b31
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
