apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: "2020-07-13T21:12:09Z"
  generation: 1
  labels:
    app: web
  name: web
  namespace: default
  resourceVersion: "1794784"
  selfLink: /apis/apps/v1/namespaces/default/deployments/web
  uid: 3f6c9ac4-81bf-48a9-925c-a33c95ac0176
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
